// SPDX-License-Identifier: MIT
pragma solidity >=0.8.28 <0.9.0;

// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// ============================================================================
// Compiler: solc 0.8.30
// EVM version: prague
// Optimizer: true (runs: 10000, via_ir: true)
// Metadata: none (bytecode_hash = "none", cbor_metadata = false)
// ============================================================================
//
// This file contains the captured creation code for BaoFactory.
// To regenerate: ./script/bao-factory --extract
//
// For deployment logic, see BaoFactoryDeployLib.sol
// For Foundry test utilities, see BaoFactoryFoundryLib.sol
// ============================================================================

/// @title BaoFactoryBytecode
/// @author Bao Finance
/// @notice Captured creation code and addresses for deterministic BaoFactory deployment
/// @dev Generated bytecode ensures consistent addresses regardless of compiler changes
library BaoFactoryBytecode {

    /// @dev BaoFactory salt string
    string internal constant SALT = "Bao.BaoFactory.harbor";

    /// @dev BaoFactory owner (Harbor multisig)
    address internal constant OWNER = 0x9bABfC1A1952a6ed2caC1922BFfE80c0506364a2;

    /// @dev BaoFactory creation code
    // slither-disable-next-line too-many-digits
    bytes internal constant CREATION_CODE =
        hex"60a0346100d357306080527fcc3735a920a3ca505d382bbc545af43d6000803e6038573d6000fd5b3d6000f36060527f5155f3363d3d373d3d363d7f360894a13ba1a3210667c828492db98dca3e207660405261600960205230601e5268603d3d8160223d3973600a52605f60215ff080156100c657816040525f606052309060018060a01b03167ff80af8aa8e2d55a4045822f47322a44efa88490b7de71dfb23510bbd4f1b578d5f80a36102f290816100d8823960805181818160bb01526101a30152f35b63301164255f526004601cfd5b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c80634f1ef2861461011657806352d1902d1461008a57638da5cb5b1461003a575f80fd5b34610086575f7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc360112610086576020604051739babfc1a1952a6ed2cac1922bffe80c0506364a28152f35b5f80fd5b34610086575f7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc36011261008657307f0000000000000000000000000000000000000000000000000000000000000000036101095760206040517f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc8152f35b639f03a0265f526004601cfd5b60407ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100865760043573ffffffffffffffffffffffffffffffffffffffff8116809103610086576024359067ffffffffffffffff821161008657366023830112156100865781600401359067ffffffffffffffff821161008657366024838501011161008657307f00000000000000000000000000000000000000000000000000000000000000001461010957739babfc1a1952a6ed2cac1922bffe80c0506364a233036102ca5780156102a2573d5f526352d1902d6001527f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc602060016004601d855afa510361029457807fbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b5f80a281817f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc5561027457005b815f926024604051950185378338925af41561028c57005b3d5f823e3d90fd5b6355299b496001526004601dfd5b7fe6c4247b000000000000000000000000000000000000000000000000000000005f5260045ffd5b7f82b42900000000000000000000000000000000000000000000000000000000005f5260045ffd";

    /// @dev keccak256 of CREATION_CODE
    bytes32 internal constant CREATION_CODE_HASH = 0xe021984d0e3e101ff54c133beb92b957ae95285b96bee5d621cefca89d99a3c2;

    /// @dev Predicted implementation address (depends on SALT and CREATION_CODE_HASH)
    address internal constant PREDICTED_IMPLEMENTATION = 0x8EB45CaD242Cecdcc9FcC9F1b2A301245566bD0E;

    /// @dev Predicted proxy address (depends on PREDICTED_IMPLEMENTATION)
    address internal constant PREDICTED_PROXY = 0xD696E56b3A054734d4C6DCBD32E11a278b0EC458;
}
